
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-08T16:39:57+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "bcc7f670d6ca71ba13ebf6fa1bf334d014ee520a",
 "version": "0.0.4+56.gbcc7f67"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
